### ISSUE TITLE
Error running hook during fetch

### ISSUE THREAD

**Issue by lucianoluzzi** [threema-ch/webrtc-build-docker#29]
Hello!
I have tried three or four times running ./cli.sh fetch, but everytime I get the error below:
`Hook 'download_from_google_storage --directory --recursive --num_threads=10 --no_auth --quiet --bucket chromium-webrtc-resources src/resources' took 1596.33 secs
Error: Command 'vpython src/testing/generate_location_tags.py --out src/testing/location_tags.json' returned non-zero exit status 249 in /webrtc
ERRO[7196] error waiting for container: invalid character 'u' looking for beginning of value `

**Comment by lgrahl** [comment]
Sounds like a Docker issue. A quick search shows correlation with https://github.com/docker/for-mac/issues/5139
